name: Tests and Coverage

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.14.x', '1.13.x', '1.12.x', '1.11.x', '1.10.x', '1.9.x', '1.8.x' ]
    name: Test with Go v${{ matrix.go }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Check out code the Go-Way
        run: go get github.com/${GITHUB_REPOSITORY}
      - name: Setup
        run: |
          cd ~/go/src/github.com/${GITHUB_REPOSITORY}
          go get -v -t -d ./...
          go get golang.org/x/tools/cmd/cover
          go get github.com/mattn/goveralls
          go install -v github.com/mattn/goveralls
      - name: Test
        run: |
          cd ~/go/src/github.com/${GITHUB_REPOSITORY}
          go test -v -parallel=10 -covermode=count -coverprofile=coverage.out
      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd ~/go/src/github.com/${GITHUB_REPOSITORY}
          goveralls -coverprofile=coverage.out -service=github
