name: Tests and Coverage

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.16.x', '1.15.x', '1.14.x', '1.13.x', '1.12.x' ]
    name: Test with Go v${{ matrix.go }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Setup
        run: |
          go get golang.org/x/tools/cmd/cover
          go get github.com/mattn/goveralls
      - name: Test
        run: |
          go test -v -parallel=10 -covermode=count -coverprofile=coverage.out
      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          goveralls -coverprofile=coverage.out -service=github
